In [1]:
import pandas as pd
import numpy as np
import sympy as sp

In [2]:
np.random.seed(50)
A= np.random.randint(0,10,(6,6))
sp.Matrix(A)

Matrix([
[0, 0, 1, 4, 6, 5],
[6, 6, 5, 2, 7, 4],
[3, 6, 4, 1, 5, 9],
[0, 6, 3, 2, 9, 3],
[3, 3, 2, 0, 3, 2],
[0, 3, 0, 0, 7, 3]])

# Perform Singular Value Decomposition on the matrix A

In [ ]:
U,s,Vt=np.linalg.svd(A)

In [4]:
sp.Matrix(np.round(U))

Matrix([
[ 0.0, 1.0, -1.0, 1.0,  0.0,  0.0],
[-1.0, 0.0,  0.0, 1.0,  0.0,  0.0],
[-1.0, 0.0, -1.0, 0.0,  0.0,  0.0],
[ 0.0, 0.0,  0.0, 0.0,  1.0,  0.0],
[ 0.0, 0.0,  0.0, 0.0,  0.0, -1.0],
[ 0.0, 0.0,  0.0, 0.0, -1.0,  0.0]])

In [13]:
sp.Matrix(np.diag(s))

Matrix([
[23.5453282689798,              0.0,              0.0,              0.0,              0.0,                0.0],
[             0.0, 6.99532786526327,              0.0,              0.0,              0.0,                0.0],
[             0.0,              0.0, 5.48913713685966,              0.0,              0.0,                0.0],
[             0.0,              0.0,              0.0, 3.82737812818262,              0.0,                0.0],
[             0.0,              0.0,              0.0,              0.0, 2.21390055855326,                0.0],
[             0.0,              0.0,              0.0,              0.0,              0.0, 0.0458174306081103]])

In [19]:
Sigma=np.zeros((A.shape[0],A.shape[1]))
sp.Matrix(Sigma)

Matrix([
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])

In [20]:
Sigma[:A.shape[1],:A.shape[0]]=np.diag(s)
sp.Matrix(Sigma)

Matrix([
[23.5453282689798,              0.0,              0.0,              0.0,              0.0,                0.0],
[             0.0, 6.99532786526327,              0.0,              0.0,              0.0,                0.0],
[             0.0,              0.0, 5.48913713685966,              0.0,              0.0,                0.0],
[             0.0,              0.0,              0.0, 3.82737812818262,              0.0,                0.0],
[             0.0,              0.0,              0.0,              0.0, 2.21390055855326,                0.0],
[             0.0,              0.0,              0.0,              0.0,              0.0, 0.0458174306081103]])

In [15]:
sp.Matrix(np.round(Vt))

Matrix([
[ 0.0, 0.0,  0.0, 0.0, -1.0,  0.0],
[-1.0, 0.0,  0.0, 0.0,  1.0,  0.0],
[ 0.0, 0.0,  0.0, 0.0,  0.0, -1.0],
[ 0.0, 0.0,  0.0, 1.0,  0.0,  0.0],
[-1.0, 0.0,  1.0, 0.0,  0.0,  0.0],
[ 0.0, 0.0, -1.0, 0.0,  0.0,  0.0]])

In [21]:
# verification of SVD
y=U@Sigma@Vt
sp.Matrix(y)

Matrix([
[-8.88178419700125e-16, -3.5527136788005e-15,                  1.0,                   4.0, 6.0, 5.0],
[                  6.0,                  6.0,                  5.0,                   2.0, 7.0, 4.0],
[                  3.0,                  6.0,                  4.0,                   1.0, 5.0, 9.0],
[-4.44089209850063e-16,                  6.0,                  3.0,                   2.0, 9.0, 3.0],
[                  3.0,                  3.0,                  2.0,  -2.1094237467878e-15, 3.0, 2.0],
[-1.33226762955019e-15,     2.99999999999999, 4.88498130835069e-15, -3.99680288865056e-15, 7.0, 3.0]])

In [22]:
sp.Matrix(A)

Matrix([
[0, 0, 1, 4, 6, 5],
[6, 6, 5, 2, 7, 4],
[3, 6, 4, 1, 5, 9],
[0, 6, 3, 2, 9, 3],
[3, 3, 2, 0, 3, 2],
[0, 3, 0, 0, 7, 3]])

A equals the product of U, Σ, and V.

# Rank 2 and Rank 3 approximations of matrix A.

In [24]:
for k in range(2,4):
    Ak= np.dot(U[:,:k], np.dot(np.diag(s[:k]), Vt[:k,:]))
    print(f"rank-{k} approximation of A:\n {Ak}\n")

rank-2 approximation of A:
 [[-0.79894314  2.15169025  0.74683769  2.02385124  6.70547621  3.16322487]
 [ 4.78176718  6.42897995  4.64711333  1.18412039  6.1135535   5.88493814]
 [ 4.32935918  6.20254239  4.3877423   1.33505157  6.44971151  5.81894027]
 [ 0.82240234  4.27120035  2.294027    2.38378284  8.63382375  5.08104335]
 [ 2.47165287  3.03068558  2.26397845  0.41068287  2.45965821  2.66602718]
 [-0.24752239  2.44715319  1.07216688  1.85329552  6.34237936  3.26869075]]

rank-3 approximation of A:
 [[-1.05684147  1.08091566  0.59260402  2.64845723  5.71061603  5.57216469]
 [ 4.92947406  7.04224786  4.73544804  0.82638794  6.68334273  4.50525889]
 [ 4.03789751  4.99241535  4.21343639  2.04094486  5.32537852  8.54138365]
 [ 1.04799589  5.20784789  2.4289411   1.83741606  9.50406605  2.97385143]
 [ 2.54703963  3.34368577  2.30906279  0.22810309  2.75046772  1.96186532]
 [-0.1571777   2.82225759  1.12619668  1.63448901  6.69089008  2.42481201]]

